# rss: may be RSS/Atom

- name: Dilbert
  source_link: http://dilbert.com
  rss: http://feed.dilbert.com/dilbert/daily_strip?format=xml

- name: Looking for Group
  source_link: http://www.lfgcomic.com/
  rss: http://feeds.feedburner.com/LookingForGroup?format=xml
  meta:
    filter:
      feedburner_origLink: /page/\d+$

- name: Calvin & Hobbes
  source_link: http://www.gocomics.com/calvinandhobbes
  rss: http://feeds.feedburner.com/uclick/calvinandhobbes?format=xml
  meta:
    image_xpath: "//meta[@name='twitter:image']/@content"

- name: xkcd
  source_link: http://xkcd.com
  rss: http://xkcd.com/atom.xml