# rss: may be RSS/Atom

- name: Dilbert
  source_link: http://dilbert.com
  rss: http://feed.dilbert.com/dilbert/daily_strip?format=xml
  meta:
    css: junkbuster

- name: Looking for Group
  source_link: http://www.lfgcomic.com/
  rss: http://feeds.feedburner.com/LookingForGroup?format=xml
  meta:
    filter:
      feedburner_origLink: /page/\d+$

- name: Calvin & Hobbes
  source_link: http://www.gocomics.com/calvinandhobbes
  rss: http://feeds.feedburner.com/uclick/calvinandhobbes?format=xml
  meta:
    image_xpath: "//meta[@name='twitter:image']/@content"

- name: xkcd
  source_link: http://xkcd.com
  rss: http://xkcd.com/atom.xml

- name: The Order of the Stick
  source_link: http://www.giantitp.com/comics/oots.html
  rss: http://www.giantitp.com/comics/oots.rss
  meta:
    image_xpath: "//img/@src"
    image_filter: (?i)comics/images/.*.gif$

- name: Girl Genius
  source_link: http://www.girlgeniusonline.com/comic.php
  rss: http://www.girlgeniusonline.com/ggmain.rss
  meta:
    image_xpath: "//img/@src"
    image_filter: (?i)ggmain/strips/.*.jpg

- name: Questionable Content
  source_link: http://www.questionablecontent.net/
  rss: http://www.questionablecontent.net/QCRSS.xml
  meta:
    css: junkbuster

- name: Goblins
  source_link: http://goblinscomic.com/
  rss: http://goblinscomic.com/feed/
  meta:
    filter:
      link: goblinscomic.com/\d+/?$

- name: Penny Arcade
  source_link: http://www.penny-arcade.com/comic/
  rss: http://penny-arcade.com/feed
  meta:
    filter:
      link: /comic/
    image_xpath: "//div[@class='post comic']/img/@src"